title = "Tim Jones Blog"
baseURL = "https://timjones1.github.io/"
languageCode = "en-uk"
theme = "ananke"


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
publishDir = "docs"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Where I blog about machine learning, data science and various other topis of interest"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/timjones1/"
  gitlab = ""
  linkedin = "tim"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/white-island_2.jpg"
  recent_posts_number = 3
